version: '3.9'
services:
  react:
    container_name: react
    privileged: true
    restart: always
    stdin_open: true
    tty: true
    command: /bin/sh
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./react/src:/usr/src/app